modes:  # 选择网络、损失函数，是否训练
    method: 'TransformerLSTM'
    path: 'best'
    loss: 'loss_CE'
    train: True
    ddp: False
data_settings:  # 数据读取载入方式，用于设置data_loader
    dataset: 'RML2018'
    Xmode:
        type: 'AP'
        options:
            IQ_norm: False  # 归一化到[0, 1]
            zero_mask: False
            random_mix: False
    mod_type: [ '32PSK', '16APSK', '32QAM', 'FM', 'GMSK', '32APSK', 'OQPSK', '8ASK', 'BPSK', '8PSK', 'AM-SSB-SC',
    '4ASK', '16PSK', '64APSK', '128QAM', '128APSK', 'AM-DSB-SC', 'AM-SSB-WC', '64QAM', 'QPSK', '256QAM',
    'AM-DSB-WC', 'OOK', '16QAM' ]
opt_params:  # 网络训练参数
    batch_size: 512
    epochs: 150
    lr: 1e-3
    workers: 8
    seed: 1
    gpu: 0
    cpu: False
    early_stop: False